image_width: 480
image_height: 640
camera_name: dfc
camera_matrix:
  rows: 3
  cols: 3
  data: [275.00, 0.0, 320.00, 0.0, 275.00, 240.00, 0.0, 0.0, 1.0]
distortion_model: fisheye
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.003908, -0.009574, 0.010173, -0.003329]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
